### ISSUE TITLE
不能添加redemo-md文档元素的class

### ISSUE THREAD

**Issue by HexMox** [gwuhaolin/redemo#1]
为了使md语法具有样式，github-markdown.css，需要对渲染出来div.redemo-md元素增加markdwon-body类名。

**Comment by gwuhaolin** [comment]
add support in 
https://github.com/gwuhaolin/redemo/commit/3cecefd1a303a1718b4ad8a0dae91ebdd44e1609

add a prop named `mdClassName` to pass prop to markdown.
